version: '2'
services:
  kibana:
    image: graanjonlo/kibana:6.2.2
    ports:
     - "5601:5601"
    expose:
     - "5601"
    volumes:
     - "/home/andy/docker/data/kibana:/data"
     - "/home/andy/docker/logs/kibana:/var/logs/kibana"
    environment:
     - ES_HOST=localhost
